FROM mcr.microsoft.com/cosmosdb/ubuntu/documentdb-oss:base

WORKDIR /home/documentdb/code  

COPY . /home/documentdb/code  

RUN git config --global --add safe.directory /home/DocumentDB/code
RUN make  && sudo make install
  
# Set the entry point to run the new script at container startup  
ENTRYPOINT ["/home/documentdb/code/scripts/start_services.sh"]  
