ARG BASE_IMAGE=redhat/ubi8:latest
FROM ${BASE_IMAGE}

ARG POSTGRES_VERSION=16
ARG RPM_PACKAGE_REL_PATH

# Install EPEL and PostgreSQL repository
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN yum install -y https://download.postgresql.org/pub/repos/yum/repopackages/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm

# Update package manager
RUN yum update -y

# Install PostgreSQL
RUN yum install -y \
    postgresql${POSTGRES_VERSION} \
    postgresql${POSTGRES_VERSION}-server \
    postgresql${POSTGRES_VERSION}-contrib \
    && yum clean all

# Copy the package to test
COPY ${RPM_PACKAGE_REL_PATH} /tmp/documentdb.rpm

COPY packaging/test_packages/test-install-entrypoint-rpm.sh /usr/local/bin/test-install-entrypoint-rpm.sh
RUN chmod +x /usr/local/bin/test-install-entrypoint-rpm.sh

ENTRYPOINT ["test-install-entrypoint-rpm.sh"]