ARG BASE_IMAGE=fedora:38
FROM ${BASE_IMAGE}

ARG POSTGRES_VERSION=16
ARG RPM_PACKAGE_REL_PATH

# Install PostgreSQL repository
RUN dnf install -y https://download.postgresql.org/pub/repos/yum/repopackages/F-38-x86_64/pgdg-fedora-repo-latest.noarch.rpm

# Update package manager
RUN dnf update -y

# Install PostgreSQL
RUN dnf install -y \
    postgresql${POSTGRES_VERSION} \
    postgresql${POSTGRES_VERSION}-server \
    postgresql${POSTGRES_VERSION}-contrib \
    && dnf clean all

# Copy the package to test
COPY ${RPM_PACKAGE_REL_PATH} /tmp/documentdb.rpm

COPY packaging/test_packages/test-install-entrypoint-rpm.sh /usr/local/bin/test-install-entrypoint-rpm.sh
RUN chmod +x /usr/local/bin/test-install-entrypoint-rpm.sh

ENTRYPOINT ["test-install-entrypoint-rpm.sh"]