name: Build RPM packages
concurrency:
  group: build-rpm-packages-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.devcontainer/**'
      - '*.md'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'packaging/**'
      - 'scripts/**'


jobs:
  build-rpm-packages:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.os }}-${{ matrix.arch }}-pg${{ matrix.pg_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [rhel8, rhel9]
        arch: [amd64]
        include:
          - arch: amd64
            runner: ubuntu-24.04
        pg_version:
          - 16
          - 17

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract and Format Default Version
        id: extract_version
        run: |
          DOCUMENTDB_VERSION=$(grep -E "^default_version" pg_documentdb_core/documentdb_core.control | sed -E "s/.*'([0-9]+\.[0-9]+-[0-9]+)'.*/\1/")
          DOCUMENTDB_VERSION=$(echo $DOCUMENTDB_VERSION | sed "s/-/./g")
          echo "Extracted Version: $DOCUMENTDB_VERSION"
          echo "DOCUMENTDB_VERSION=$DOCUMENTDB_VERSION" >> $GITHUB_ENV

      - name: Build RPM Package
        run: |
          ./packaging/build_packages.sh --os ${{ matrix.os }} --pg ${{ matrix.pg_version }} --version ${{ env.DOCUMENTDB_VERSION }} --test-clean-install

      - name: Sign RPM packages
        run: |
          sudo apt-get update && sudo apt-get install -y rpm gnupg2
          gpg --batch --passphrase '' --quick-gen-key 'DocumentDB RPM Package Signing <documentdb@noreply.github.com>' rsa2048 sign 1y
          echo "%_gpg_name DocumentDB RPM Package Signing" >> ~/.rpmmacros
          echo "%_gpg_path /home/runner/.gnupg" >> ~/.rpmmacros
          echo "%_signature gpg" >> ~/.rpmmacros
          echo "%__gpg_sign_cmd %{__gpg} gpg --batch --yes -u \"%{_gpg_name}\" -sbo %{__signature_filename} --digest-algo sha256 %{__plaintext_filename}" >> ~/.rpmmacros
          for rpm_file in packaging/*.rpm; do
            [ -f "$rpm_file" ] && rpm --addsign "$rpm_file"
          done
          gpg --armor --export "DocumentDB RPM Package Signing" > packaging/documentdb-rpm-signing-key.asc

      - name: Upload RPM Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-pg${{ matrix.pg_version }}-documentdb-${{ env.DOCUMENTDB_VERSION }}
          path: |
            packaging/*.rpm
            packaging/documentdb-rpm-signing-key.asc
          retention-days: 7
          if-no-files-found: error
          compression-level: 0